package gameobjects;

/**
 *
 */
public enum CarreauRoom {
    VIDE,
    OBSTACLE_PIQUE,
    OBSTACLE_ROCHER,
    OBJET_CONSOMMABLE_PIECE_1,
    OBJET_CONSOMMABLE_PIECE_5,
    OBJET_CONSOMMABLE_PIECE_10,
    OBJET_CONSOMMABLE_COEUR_1,
    OBJET_CONSOMMABLE_COEUR_DEMI,
    PORTE_GAUCHE,
    PORTE_DROITE,
    PORTE_BAS,
    PORTE_HAUT,
    MONSTRE_SPIDER,
    MONSTRE_FLY,
    MONSTRE_BOSS,
};
